name: Scan Image

on: [push]

jobs:
  local-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest

    - name: Scan image
      id: scan
      uses: sysdiglabs/scan-action@v5
      with:
          image-tag: sysdiglabs/dummy-vuln-app:latest
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: https://eu1.app.sysdig.com
          cli-scanner-version: 1.18.0
          extra-parameters: "--output-json=./test.json"

    - name: Display Scan Report
      run: cat ${{ steps.scan.outputs.scanReport }}
      
    - name: Display Scan Report custom
      run: cat ${{ github.workspace }}/test.json

    - name: Display Scan Report hardcoded
      run: cat ${{ github.workspace }}/scan-result.json
   
    - name: Upload SARIF file
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/sarif.json